Create py.typed
This will make the package PEP 561 compliant so that I can run mypy on my codebase that uses instructor without losing types.

For example, this is what I see 

```
poetry run mypy .
chatlab/views/tools.py:18: error: Skipping analyzing "instructor.dsl.partialjson": module is installed, but missing library stubs or py.typed marker  [import-untyped]
chatlab/__init__.py:35: error: Skipping analyzing "instructor": module is installed, but missing library stubs or py.typed marker  [import-untyped]
chatlab/__init__.py:35: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 2 errors in 2 files (checked 26 source files)
```